[package]
name = "rustenstein"
version = "0.1.0"
authors = ["Wilmer Finol"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.2"
