[package]
name = "rustenstein"
version = "0.1.0"
authors = ["Wilmer Finol"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.2"
image = "0.23.8"
wgpu = "0.6.0"
futures = "0.3.5"
env_logger = "0.7"
